---
title: "Text Analyis"
output: github_document
---

```{r}
all_tweets <- read.csv("Trump.csv")
```

```{r}
library(dplyr)

only_trump_tweets <- all_tweets %>%
  filter(is_retweet == "FALSE") 
```

```{r}
library(stringr)
library(rebus)

clean_words <- only_trump_tweets[ , 2] %>%
  str_split(pattern = fixed(" ")) %>%
  unlist() %>%
  str_replace_all(pattern = "\\W", replacement = "") %>%
  str_replace_all(pattern = "http.*", replacement = "")
```

```{r}
clean_words_df <- data_frame(word = clean_words) %>%
  filter(!(word == ""))
word_count <- clean_words_df %>%
  count(word, sort = T) 

```

```{r}
library(ggplot2)

ggplot(word_count[1:20, ], aes(word, n)) +
      geom_point()
```

```{r}
library(tidytext)

trump_sentiment_nrc <- word_count %>%
  inner_join(get_sentiments("nrc"))

trump_sentiment_bing <- word_count %>%
  inner_join(get_sentiments("bing"))

trump_sentiment_afinn <- word_count %>%
  inner_join(get_sentiments("afinn"))

ggplot(word_count[1:20, ], aes(word, n)) +
      geom_point()
```

```{r}
library(tidytext)

nrc_positive <- trump_sentiment_nrc  %>%
  filter(sentiment == "positive")

nrc_positive[1:10, ] %>%
  top_n(10) %>%
  mutate(word = reorder(word, n)) %>%
  # Use aes() to put words on the x-axis and frequency on the y-axis
  ggplot(aes(word, n)) +
  # Make a bar chart with geom_col()
  geom_col() +
  coord_flip() 
```

```{r}
bing_positive <- trump_sentiment_bing  %>%
  filter(sentiment == "positive")

bing_positive[1:10, ] %>%
  mutate(word = reorder(word, n)) %>%
  # Use aes() to put words on the x-axis and frequency on the y-axis
  ggplot(aes(word, n)) +
  # Make a bar chart with geom_col()
  geom_col() +
  coord_flip() 
```

